version: '3.8'

services:

  app:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/report_app
      - LATEX_COMPILER=windows_local  # Используем TeX Live на Windows хосте
      - TEXLIVE_PATH=C:/texlive/2025/bin/windows/xelatex.exe  # Путь к компилятору
    depends_on:
      - db
    volumes:
      # Монтируем папку для PDF (будет на Windows хосте)
      - ./media:/app/media
      # Для разработки - монтируем код
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    container_name: report_db_container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=report_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: